### ISSUE TITLE
Hub agent for MCS controller

### ISSUE THREAD

**Issue by elevran** [axon-submariner/lighthouse#2]
Migrate Submariner to use an active hub component instead of having the Broker solely for passive maintenance of "shared state". This is complementary to work done in #1.
The controller focuses on MCS objects. Other Hub controllers can/will be created for other tasks (e.g., tenant and cluster management, IPSec certificate management, etc.)

## High Level Tasks

- [x] HLD
- [x] skeleton with RBAC permissions (watch single broker namespace for ServiceExports and EndpointSlices. Assuming read-only access by anything other than our controller, including spoke clusters, Imports are explicitly not watched and are assumed to be always in-sync)
- [x] ServiceExport maintains 1:1 mapping with imports (i.e., one import for every cluster exporting the service)
   - [x] created/modified: ensure compatible if there are existing exports for ns/svc; if conflicting - set export.Status to `Conflict` otherwise create/update ServiceImport with fields from annotations and labels of Export and add cluster to `import.Status.Clusters` (this is redundant with the sourceCluster label and labels on the EndpointSlice. In the future we can merge multiple Imports on the hub, instead of producing an import per export).
   - [x] deleted: remove corresponding ServiceImport (and EndpointSlices? Or is this done later by the spoke?)
- [x] EndpointSlice controller *might* be needed (need to better understand these flows - it's possible that uploaded Slices from one spoke can just be fetched as-is by the other spokes)

## Assumptions

1. Hub RBAC
   - ServiceExport: Read
   - ServiceExport/Status: Update
   - ServiceImport: Create, Read, Update, Delete
   - ServiceImport/Status: Read, Update
   - EndpointSlice: Read?
2. Spoke RBAC - all confined to single namespace, all spokes have the same Role:
   - ServiceExport: Create, Read, Update, Delete
   - ServiceExport/Status: Read
   - ServiceImport: Read
   - EndpointSlice: Create, Read, Update, Delete
3. Properties on ServiceExport published to hub capture Service context that's needed (e.g., Service Name, Namespace, Ports, Headlessness, ... in addition it includes a creationTimestamp copied from the Spoke and used for conflict resolution)

**Comment by davidohana** [comment]
> Imports are explicitly not handled to be always in-sync 

Can you explain "not handled to be always in-sync " ?

**Comment by davidohana** [comment]
> ServiceImport/Status: Update

What updates are expected that the spoke will make on import status?
In MCS spec,  ServiceImport Status has only `Clusters`

```go
// ServiceImportStatus describes derived state of an imported service.
type ServiceImportStatus struct {
  // +optional
  // +patchStrategy=merge
  // +patchMergeKey=cluster
  // +listType=map
  // +listMapKey=cluster
  Clusters []ClusterStatus `json:"clusters"`
}
```

**Comment by elevran** [comment]
> Can you explain "not handled to be always in-sync " ?
Missing "not handled since they're assumed to be ..." - added to text

> What updates are expected that the spoke will make on import status?
Removed. Nothing is expected. The set of exporting Clusters can and should be set by Hub on the Import.

**Comment by elevran** [comment]
will be completed when #26 is merged
